In [4]:
import numpy as np

## Projections

Projections on a closed convex set, are very useful for many optimization problems. Instead of solving the unconstrained problem
$$
\min_x f(x)
$$
you can solve the constrained problem:
$$
\min_{x} f(x) \text{ subject to } x \in \mathcal{C}
$$
That leads to a gradient method which iterativly solves:
$$
y_{k+1} = x_k - \alpha_k \nabla f(x_k) \\
x_{k+1} = \arg\min_{x \in \mathcal{C}} || y_{k+1} - x ||
$$

However, for closed convext sets this simplifies to a simple projection operator $\mathcal{P}_\mathcal{C}$. This exercise, talks one special interesting such projection operator.

#### Box Projection

The orthogonal projection onto a box:
$$
 \operatorname{Box}_{[l, u]} = \{ x: l \leq x\leq u \}
$$
is defined as:
$$
P_{\operatorname{Box}_{[l, u]}} (x_i) = min\{ max \{x_i, l_i\}, u_i \} =
        \begin{cases}
        l_i, & x_i < l_i\\
        x_i,& l_i \leq x_i \leq u_i \\
        u_i,  & x_i > u_i\\
        \end{cases} \quad \forall i
$$

Implement a function that takes an input vector and orthogonal projection onto the box set!

In [7]:
def box(x, l, u):
    """
    Box projection
    """
    return np.minimum(np.maximum(x, l), u)

x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5]])
a = box(x, 3, 8)
print(a)

[[3 3 3 4 5]
 [6 7 8 8 8]
 [3 3 3 4 5]]


### Brainstorm

For different applications (e.g. X-ray CT, denoising, deconvolution), does the box projection make sense for them? If so, what values for the lower and upper bound do make sense? Is that a general statement, or can that only happen in special cases?